### ISSUE TITLE
Add more stuff

### ISSUE THREAD

**Issue by AmirulAndalib** [wy580477/Heroku-All-In-One-APP#13]
Hi please add Qbittorrent webui 

https://github.com/developeranaz/qbittorrent-to-rclone-heroku

**Comment by AmirulAndalib** [comment]
Please also add Jellyfin with config as Heroku restart deletes Everything @wy580477

**Comment by AmirulAndalib** [comment]
Also jackett on Heroku 

https://github.com/l3v11/Jackett-heroku

Mentioned

**Comment by kamileecher** [comment]
https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku

and this perfect

**Comment by wy580477** [comment]
> Hi please add Qbittorrent webui

What fuction you need in qbittorrent, I will look into if aria2 can support needs before adding another downloader.

> Please also add Jellyfin with config as Heroku restart deletes Everything 

Deploying Jellyfin on heroku is not a good idea，it has high memory usage(200MB-300MB while idling).

> Also jackett on Heroku

I'll look into this.

> https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku

I'm not familiar with Jdownloader. What advantage does it offer over yt-dlp?

**Comment by AmirulAndalib** [comment]
> > Hi please add Qbittorrent webui
> 
> What fuction you need in qbittorrent, I will look into if aria2 can support needs before adding another downloader.
> 
> > Please also add Jellyfin with config as Heroku restart deletes Everything
> 
> Deploying Jellyfin on heroku is not a good idea，it has high memory usage(200MB-300MB while idling).
> 
> > Also jackett on Heroku
> 
> I'll look into this.
> 
> > https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku
> 
> I'm not familiar with Jdownloader. What advantage does it offer over yt-dlp?

Leave jellyfin but qbitorrent is the best only torrent downloader focused on downloading torrents only

**Comment by AmirulAndalib** [comment]
Need this Terminal on Heroku too so that we can zip and configure other stuff from The terminal

https://github.com/history2/heroku-ttyd

**Comment by AmirulAndalib** [comment]
Todo:



> > Hi please add Qbittorrent webui
> 
> What fuction you need in qbittorrent, I will look into if aria2 can support needs before adding another downloader.
> 
> > Please also add Jellyfin with config as Heroku restart deletes Everything
> 
> Deploying Jellyfin on heroku is not a good idea，it has high memory usage(200MB-300MB while idling).
> 
> > Also jackett on Heroku
> 
> I'll look into this.
> 
> > https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku
> 
> I'm not familiar with Jdownloader. What advantage does it offer over yt-dlp?

Jdownloader is more of like aria2c but can catch link shorteners or download files like from mega.nz onefichier etc

**Comment by AmirulAndalib** [comment]
# Todo:

---

- [ ] ***[Add Jdownloader](https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku)***

- [ ] ***[Add Qbittorrent](https://github.com/developeranaz/qbittorrent-to-rclone-heroku)***

- [ ] ***[Add Jackett Rss](https://github.com/l3v11/Jackett-heroku)*** 
---

**Comment by wy580477** [comment]
After some research among headless torrent clients, transmisson will be added later. It's very lightweight and suitable for headless mode.

**Comment by AmirulAndalib** [comment]
Qbit is a must please add it and it's suitable for headless mode aria2c is Based for Direct download links only

**Comment by SonaliBendre** [comment]
> After some research among headless torrent clients, transmisson will be added later. It's very lightweight and suitable for headless mode.

rtorrent please. flood is a nice web-ui for rtorrent. transmission sucks

**Comment by SonaliBendre** [comment]
Consider Cloudreve?

**Comment by wy580477** [comment]
> Consider Cloudreve?

I tried it for a while, hate it.

1. It needs persistent database, not suitable for heroku free tier.
2. It can't configured as a subpath behind reverse proxy.
3. It doesn't support tls connection to database, you can‘t directly connect to free database services outside heroku. 

Maybe I try to use nginx as tcp reverse proxy for external database connection in the future,  but I don't think there's huge demand for it.

If you want to run cloudreve, running on VPS is the proper way.

**Comment by AmirulAndalib** [comment]
You can just mount Rclone it will show on Filebrowser

**Comment by wy580477** [comment]
> You can just mount Rclone it will show on Filebrowser

No, you can't do this on heroku.  

1. Heroku's linux kernel doesn't have fuse module which is needed for rclone mount.
2. Even if kernel has necessary modules, you still need root access to mount the filesystem.

I have tried several PaaS platforms,  you can't run rclone mount on them.

**Comment by AmirulAndalib** [comment]
Sad

**Comment by AmirulAndalib** [comment]
Open a discussion and let's there or a telegram support group it's getting spammy here
